import type { ExerciseItem } from '../types';

export const INITIAL_EXERCISES: ExerciseItem[] = [
  {
    id: 'exc-1',
    name: 'Sentadillas con Peso Corporal',
    category: 'Fuerza',
    muscleGroup: 'Piernas y Glúteos',
    difficulty: 'Principiante',
    metValue: 5.0,
    recommendedDurationMin: 15,
    description: 'Ejercicio funcional fundamental para tren inferior y estabilidad del core.',
    isActive: true,
  },
  {
    id: 'exc-2',
    name: 'Caminata Rápida en Cinta (6 km/h)',
    category: 'Cardio',
    muscleGroup: 'Cardiovascular / Todo el cuerpo',
    difficulty: 'Principiante',
    metValue: 4.3,
    recommendedDurationMin: 30,
    description: 'Actividad aeróbica de bajo impacto ideal para control metabólico y quema de grasa.',
    isActive: true,
  },
  {
    id: 'exc-3',
    name: 'Plancha Abdominal Isométrica',
    category: 'Fuerza',
    muscleGroup: 'Core / Abdominales',
    difficulty: 'Intermedio',
    metValue: 3.8,
    recommendedDurationMin: 10,
    description: 'Trabajo isométrico para fortalecimiento profundo del cinturón abdominal y columna.',
    isActive: true,
  },
  {
    id: 'exc-4',
    name: 'Intervalos HIIT en Bicicleta Estática',
    category: 'HIIT',
    muscleGroup: 'Piernas / Cardiovascular',
    difficulty: 'Avanzado',
    metValue: 9.5,
    recommendedDurationMin: 20,
    description: 'Entrenamiento de alta intensidad con intervalos de 30s sprint / 60s recuperación activa.',
    isActive: true,
  },
  {
    id: 'exc-5',
    name: 'Estiramiento Dinámico de Cadera e Isquiotibiales',
    category: 'Flexibilidad',
    muscleGroup: 'Cadera e Isquiotibiales',
    difficulty: 'Principiante',
    metValue: 2.3,
    recommendedDurationMin: 15,
    description: 'Rutina de movilidad articular y elongación para prevenir lesiones y dolor lumbar.',
    isActive: true,
  },
  {
    id: 'exc-6',
    name: 'Press con Mancuernas en Banco Inclinado',
    category: 'Fuerza',
    muscleGroup: 'Pecho, Hombros y Tríceps',
    difficulty: 'Intermedio',
    metValue: 6.0,
    recommendedDurationMin: 25,
    description: 'Desarrollo de fuerza del tren superior enfocándose en haz clavicular pectoral.',
    isActive: true,
  },
  {
    id: 'exc-7',
    name: 'Remo con Banda de Resistencia',
    category: 'Rehabilitación',
    muscleGroup: 'Espalda Alta y Postura',
    difficulty: 'Principiante',
    metValue: 3.5,
    recommendedDurationMin: 15,
    description: 'Ejercicio correctivo postural para retracción escapular y fortalecimiento de romboides.',
    isActive: true,
  },
  {
    id: 'exc-8',
    name: 'Ejercicios de Equilibrio sobre Bosu',
    category: 'Equilibrio',
    muscleGroup: 'Propiocepción / Tobillos',
    difficulty: 'Intermedio',
    metValue: 3.0,
    recommendedDurationMin: 15,
    description: 'Mejora de la estabilidad articular y control neuromuscular sobre superficie inestable.',
    isActive: true,
  },
];
